### PR TITLE
Benji Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by thebenjii**

### CODE REVIEW

**Comment by thebenjii** [comment]
Thanks

**Review by blwatkins — CHANGES_REQUESTED** [review]
Please resolve merge conflicts.

**Review by blwatkins — CHANGES_REQUESTED** [review]
Please resolve merge conflicts.  The changes in this pull request should not remove the names of any other contributors.

**Review by blwatkins — CHANGES_REQUESTED** [review]
Please resolve merge conflicts and update changes. The changes in this pull request should not remove the names of any other contributors.

Comment Date: Friday, October 18, 2024

**Review by blwatkins — CHANGES_REQUESTED** [review]
Please resolve merge conflicts and update changes. The changes in this pull request should not remove the names of any other contributors.

Comment Date: Wednesday, November 27, 2024

**Pull request closed without merging**
