### PR TITLE
Added name to contributors

### PR DESCRIPTION
**Pull request by jayeryden**

### CODE REVIEW

**Review by blwatkins — CHANGES_REQUESTED** [review]
Please resolve merge conflicts.

**Comment by jayeryden** [comment]
Fixed merge conflicts

**Review by blwatkins — CHANGES_REQUESTED** [review]
Please resolve additional merge conflicts 

(Date of Comment: Friday, October 18, 2024)

**Comment by jayeryden** [comment]
This should be fixed now, I got rid of my changes in portfolio.md, so the pull request for contributors.md should work now. I sent you and email if you could help me get this sorted out.

**Pull request closed without merging**
